INSERT INTO ORDER_USER (ORDERID, ORDER_ACCEPTED, ORDER_OUTFORDELIVERY,ORDER_RECEIVED,ORDER_DELIVERED,ORDERDATETIME,USERADDRESS,USEREMAIL,USERNAME) 
VALUES(10001,false,false,false,false,'2020-02-11 00:00:01','Haldiram','addy.1989.1aug@gmail.com','ardhendu');
INSERT INTO ORDER_USER (ORDERID, ORDER_ACCEPTED, ORDER_OUTFORDELIVERY,ORDER_RECEIVED,ORDER_DELIVERED,ORDERDATETIME,USERADDRESS,USEREMAIL,USERNAME) 
VALUES(10002,false,false,false,false,'2020-02-11 00:00:01','Haldiram','annie.1989.1aug@gmail.com','annie');
INSERT INTO ORDER_USER (ORDERID, ORDER_ACCEPTED, ORDER_OUTFORDELIVERY,ORDER_RECEIVED,ORDER_DELIVERED,ORDERDATETIME,USERADDRESS,USEREMAIL,USERNAME) 
VALUES(10003,false,false,false,false,'2020-02-11 00:00:01','Haldiram','addy.1989.1aug@gmail.com','mark');
